### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by civuaine** [gotonode/snippets#5]
3.5.2018 at 20.00 o'clock.
I'm going to do this in English since everything in your code and repository is in English...

**Package structure**
Your code's package structure is very clear and it definitely seems that each package has one responsibility that it takes care of. You have named all packages in lowercase which is correct. Wonderful!

**Packages, Classes and Methods in more detail**
You have named all classes correctly in _camelCase_. Methods' names aren't too long and they describe their purpose very well in my opinion. I especially liked the comments you have made in your code since they made much it easier to follow and clarified why certain methods or variables (even classes) were created.

All your methdos are less than 20 lines long, so you don't get checkstyle errors from them, which is very good programming! I have to say that you have made it easy to read your code, I understand the most of your methods' functions just by glancing the names of them. 

Your main class is very simple, it just builds a graphical interface. That's fine. I was wondering if you can combine packages io.github....snippets.app and io.github....snippets.ui into one? They both seem to handle something concerning about the graphical interface, so why not just put them into same package. Just my opinion though.

**Tests**
Your test coverage is extremely high and the tests also tests something clever, hence they are not just made to get test coverage level high! You have put a lot of effort on these, Great job!

**In the end**
For some reason I wasn't able to test your program in netbeans. If I try to run it, I get the following error: 

Unrecognized option: -createjar
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

I also tried to run it through jar-file, and it worked better since it opend a window but there were no testdata in it, even though there should be (reasoning from your manual and code). It says that pom.xml is missing...  Well this might just be usererror made by me, but maybe you can check this out.

Then finally: 
I'm very amazed. This is the best programming that I have seen done by a student. If you have computer science as your major keep going on and never stop learning, if you don't you perhaps want to consider changing it... just saying :)

**Comment by gotonode** [comment]
Hello fellow CS student (even if minor), and thank you for an in-depth analysis of my code!

Your words have uplifted my spirit. I personally do believe words matter, and your words mattered greatly.

Yes, I'm studying CS as a major. I've done computer programming for nearly 20 years now, and off, but never studied it at a university level. I do have a basic CS degree (2nd level) from over 10 years ago though.

If you'd like for me to review your cloud project and give my feedback on it, drop me a line. You can find my email address on my GitHub profile page. I'd be more than happy to do it since it's also a learning experience for me.

Your comment about combining "app" and "ui" has crossed my mind. This way, their exclusion from Checkstyle tests would be even more justified. But the Main class is still handling some things that aren't 100 % UI, so that would have to be changed before any potential merging. At least creating tests for the Main class is really hard, if not impossible.

I don't use NetBeans anymore myself. Or, rather, only use it where TMC is needed. If you haven't tried it out yet, I **highly** recommend testing JetBrains IntelliJ IDEA. Students can get the Professional version for free. It's the top Java IDE in the world right now, and for good reason.

I made a copy of Snippets to test it in NetBeans. I didn't want to open the original project in it since that would put NetBeans-specific files into it which would later become useless.

Okay, found the issue. One of the plugins didn't like working in NetBeans. I added comments to the "pom.xml" file to indicate that this plugin should be removed if running in NetBeans.

Your style of writing feedback would be very well suited for a teacher. Just saying. :-)

Again, thanks for the great feedback! Drop me a line if you want a free review back.

**Comment by gotonode** [comment]
I'll keep this issue open for the duration of this course so you won't miss on getting those points.
